import { Hospital, Paciente, PacienteDetalle, Medicamento } from './types';

export const MOCK_HOSPITALES: Hospital[] = [
  { id: 1, nombre: 'Hospital Universitario de Caracas (HUC)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4897, lng: -66.8894 },
  { id: 2, nombre: 'Hospital Dr. José María Vargas', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5173, lng: -66.9189 },
  { id: 3, nombre: 'Hospital Miguel Pérez Carreño', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4820, lng: -66.9610 },
  { id: 4, nombre: 'Hospital Dr. Domingo Luciani', municipio: 'Sucre', estado: 'Miranda', lat: 10.4862, lng: -66.8153 },
  { id: 5, nombre: 'Hospital Central de Maracay', municipio: 'Girardot', estado: 'Aragua', lat: 10.2522, lng: -67.5819 },
  { id: 6, nombre: 'Hospital Universitario Dr. Ángel Larralde', municipio: 'Valencia', estado: 'Carabobo', lat: 10.2241, lng: -68.0163 },
  { id: 7, merge_original: true, nombre: 'Hospital Universitario de Maracaibo', municipio: 'Maracaibo', estado: 'Zulia', lat: 10.6728, lng: -71.6353 } as any, // Mantener id: 7
  { id: 8, nombre: 'Hospital Universitario Ruiz y Páez', municipio: 'Heres', estado: 'Bolívar', lat: 8.1283, lng: -63.5414 },
  { id: 9, nombre: 'Hospital Dr. Manuel Núñez Tovar', municipio: 'Maturín', estado: 'Monagas', lat: 9.7497, lng: -63.1794 },
  { id: 10, nombre: 'Hospital Central de San Cristóbal', municipio: 'San Cristóbal', estado: 'Táchira', lat: 7.7656, lng: -72.2198 },
  
  // Nuevos centros agregados para cobertura nacional completa (Segmentación Geográfica de Emergencia)
  { id: 11, nombre: 'Hospital Central Universitario Antonio María Pineda', municipio: 'Iribarren', estado: 'Lara', lat: 10.0754, lng: -69.3172 },
  { id: 12, nombre: 'Instituto Autónomo Hospital Universitario de los Andes (IAHULA)', municipio: 'Libertador', estado: 'Mérida', lat: 8.5991, lng: -71.1448 },
  { id: 13, nombre: 'Hospital Universitario Dr. Luis Razetti (Barcelona)', municipio: 'Simón Bolívar', estado: 'Anzoátegui', lat: 10.1342, lng: -64.6853 },
  { id: 14, nombre: 'Hospital Dr. Alfredo Van Grieken', municipio: 'Miranda', estado: 'Falcón', lat: 11.4114, lng: -69.6736 },
  { id: 15, nombre: 'Hospital Universitario Antonio Patricio de Alcalá', municipio: 'Sucre', estado: 'Sucre', lat: 10.4533, lng: -64.1824 },
  { id: 16, nombre: 'Hospital Dr. Luis Ortega', municipio: 'Mariño', estado: 'Nueva Esparta', lat: 10.9575, lng: -63.8583 },
  { id: 17, nombre: 'Hospital Dr. Miguel Óraá', municipio: 'Guanare', estado: 'Portuguesa', lat: 9.0414, lng: -69.7483 },
  { id: 18, nombre: 'Hospital Universitario Dr. Pedro Emilio Carrillo', municipio: 'Valera', estado: 'Trujillo', lat: 9.3178, lng: -70.6033 },
  { id: 19, nombre: 'Hospital Dr. Luis Razetti (Barinas)', municipio: 'Barinas', estado: 'Barinas', lat: 8.6225, lng: -70.2119 },
  { id: 20, nombre: 'Hospital Dr. José María Vargas (La Guaira)', municipio: 'Vargas', estado: 'La Guaira', lat: 10.5983, lng: -66.9322 },
  { id: 21, nombre: 'Hospital Dr. Israel Ranuárez Balza', municipio: 'Juan Germán Roscio', estado: 'Guárico', lat: 9.9114, lng: -67.3581 },
  { id: 22, nombre: 'Hospital Dr. Egor Nucete', municipio: 'Ezequiel Zamora', estado: 'Cojedes', lat: 9.6533, lng: -68.5833 },
  { id: 23, nombre: 'Hospital Dr. Pablo Acosta Ortiz', municipio: 'San Fernando', estado: 'Apure', lat: 7.8933, lng: -67.4722 },
  { id: 24, nombre: 'Hospital Central Dr. Plácido Daniel Rodríguez Rivero', municipio: 'San Felipe', estado: 'Yaracuy', lat: 10.3392, lng: -68.7422 },
  { id: 25, nombre: 'Hospital Dr. José Gregorio Hernández (Puerto Ayacucho)', municipio: 'Atures', estado: 'Amazonas', lat: 5.6639, lng: -67.6256 },
  { id: 26, nombre: 'Hospital Dr. Luis Razetti (Tucupita)', municipio: 'Tucupita', estado: 'Delta Amacuro', lat: 9.0603, lng: -62.0514 },
  { id: 27, nombre: 'Ciudad Hospitalaria Dr. Enrique Tejera (CHET)', municipio: 'Valencia', estado: 'Carabobo', lat: 10.1692, lng: -68.0125 },
  { id: 28, nombre: 'Hospital General Dr. Felipe Guevara Rojas', municipio: 'Simón Rodríguez', estado: 'Anzoátegui', lat: 8.8833, lng: -64.2444 },
  { id: 29, nombre: 'Hospital Dr. Rafael Calles Sierra', municipio: 'Carirubana', estado: 'Falcón', lat: 11.6975, lng: -70.1833 },
  { id: 30, nombre: 'Hospital Dr. Raúl Leoni (Guaiparo)', municipio: 'Caroní', estado: 'Bolívar', lat: 8.3514, lng: -62.6514 },
  { id: 31, nombre: 'Hospital Dr. Victorino Santaella', municipio: 'Guaicaipuro', estado: 'Miranda', lat: 10.3139, lng: -67.0403 },
  { id: 32, nombre: 'Hospital Dr. de Niños J.M. de los Ríos', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5103, lng: -66.9031 }
];

export const MOCK_PACIENTES: PacienteDetalle[] = [
  {
    id: 1,
    nombre: 'Alejandro José Rondón Castro',
    edad: 45,
    sexo: 'Masculino',
    hospital: 'Hospital Universitario de Caracas (HUC)',
    hospital_id: 1,
    ingreso_fecha: '2026-06-25',
    estado: 'hospitalizado',
    posible_duplicado: false,
    cedula_masked: '***452',
    procedencia: 'La Vega, Caracas',
    ingreso_detalle: 'Fractura de fémur izquierdo por caída de escombros. Estable, en traumatología.'
  },
  {
    id: 2,
    nombre: 'María Elena Silva de Pérez',
    edad: 68,
    sexo: 'Femenino',
    hospital: 'Hospital Dr. Domingo Luciani',
    hospital_id: 4,
    ingreso_fecha: '2026-06-24',
    estado: 'hospitalizado',
    posible_duplicado: false,
    cedula_masked: '***908',
    procedencia: 'Petare, Edo. Miranda',
    ingreso_detalle: 'Trauma torácico cerrado leve. Monitoreo cardiológico continuo por hipertensión.'
  },
  {
    id: 3,
    nombre: 'Yusleidy del Carmen Mendoza',
    edad: 29,
    sexo: 'Femenino',
    hospital: 'Hospital Dr. José María Vargas',
    hospital_id: 2,
    ingreso_fecha: '2026-06-26',
    estado: 'alta',
    posible_duplicado: false,
    cedula_masked: '***114',
    procedencia: 'Cútira, Catia, Caracas',
    ingreso_detalle: 'Contusiones múltiples y escoriaciones superficiales. Dada de alta tras 24 horas de observación.'
  },
  {
    id: 4,
    nombre: 'Juan Bautista Delgado Uzcátegui',
    edad: 52,
    sexo: 'Masculino',
    hospital: 'Hospital Central de Maracay',
    hospital_id: 5,
    ingreso_fecha: '2026-06-25',
    estado: 'referido',
    posible_duplicado: false,
    cedula_masked: '***789',
    procedencia: 'El Limón, Edo. Aragua',
    ingreso_detalle: 'Quemaduras de segundo grado en extremidades superiores. Referido a Unidad de Quemados en Caracas.'
  },
  {
    id: 5,
    nombre: 'Francisco Javier Gil Blanco',
    edad: 37,
    sexo: 'Masculino',
    hospital: 'Hospital Miguel Pérez Carreño',
    hospital_id: 3,
    ingreso_fecha: '2026-06-24',
    estado: 'hospitalizado',
    posible_duplicado: true,
    cedula_masked: '***552',
    procedencia: 'El Valle, Caracas',
    ingreso_detalle: 'Politraumatismo generalizado. Registrado inicialmente con variaciones en su apellido.'
  },
  {
    id: 6,
    nombre: 'Francisco J. Gil Blanco',
    edad: 37,
    sexo: 'Masculino',
    hospital: 'Hospital Miguel Pérez Carreño',
    hospital_id: 3,
    ingreso_fecha: '2026-06-24',
    estado: 'hospitalizado',
    posible_duplicado: true,
    cedula_masked: '***552',
    procedencia: 'El Valle, Caracas',
    ingreso_detalle: 'Fila duplicada en revisión de cédula. Coincide con Francisco Javier Gil Blanco.'
  },
  {
    id: 7,
    nombre: 'Carmen Alicia Rodríguez Infante',
    edad: 73,
    sexo: 'Femenino',
    hospital: 'Hospital Central de San Cristóbal',
    hospital_id: 10,
    ingreso_fecha: '2026-06-25',
    estado: 'desconocido',
    posible_duplicado: false,
    cedula_masked: '***321',
    procedencia: 'Barrio Sucre, San Cristóbal',
    ingreso_detalle: 'Desorientada tras el sismo. Ingresada por vecinos de la zona. Se busca activamente a sus familiares.'
  },
  {
    id: 8,
    nombre: 'Santiago Andrés Gamarra',
    edad: 8,
    sexo: 'Masculino',
    hospital: 'Hospital Universitario Dr. Ángel Larralde',
    hospital_id: 6,
    ingreso_fecha: '2026-06-26',
    estado: 'hospitalizado',
    posible_duplicado: false,
    cedula_masked: '***994',
    procedencia: 'Naguanagua, Edo. Carabobo',
    ingreso_detalle: 'Fractura de clavícula derecha. Post-quirúrgico inmediato. Acompañado por su madre.'
  },
  {
    id: 9,
    nombre: 'Pedro Celestino Infante',
    edad: 81,
    sexo: 'Masculino',
    hospital: 'Hospital Dr. Luis Razetti',
    hospital_id: 8,
    ingreso_fecha: '2026-06-25',
    estado: 'fallecido',
    posible_duplicado: false,
    cedula_masked: '***041',
    procedencia: 'Soledad, Edo. Anzoátegui',
    ingreso_detalle: 'Paro cardiorrespiratorio refractario secundario a aplastamiento severo. Fallecido el 25/06/2026.'
  },
  {
    id: 10,
    nombre: 'Coromoto de Jesús Mendoza',
    edad: 59,
    sexo: 'Femenino',
    hospital: 'Hospital Dr. Manuel Núñez Tovar',
    hospital_id: 9,
    ingreso_fecha: '2026-06-24',
    estado: 'hospitalizado',
    posible_duplicado: false,
    cedula_masked: '***812',
    procedencia: 'La Cruz, Maturín',
    ingreso_detalle: 'Crisis hipertensiva y shock de pánico severo tras el colapso de estructura residencial cercana.'
  }
];

export const MOCK_MEDICAMENTOS: Medicamento[] = [
  {
    id: 1,
    nombre: 'Ibuprofeno 400mg',
    categoria: 'Analgésico',
    cantidad: 120,
    unidad: 'tabletas',
    hospital: 'Hospital Universitario de Caracas (HUC)',
    hospital_id: 1,
    disponible: true,
    donante: 'Cruz Roja Venezolana',
    notas: 'Uso exclusivo para pacientes admitidos por la emergencia del sismo.'
  },
  {
    id: 2,
    nombre: 'Amoxicilina + Ácido Clavulánico 875/125mg',
    categoria: 'Antibiótico',
    cantidad: 45,
    unidad: 'blisters',
    hospital: 'Hospital Dr. Domingo Luciani',
    hospital_id: 4,
    disponible: true,
    donante: 'Iniciativa Privada FarmaAyuda',
    notas: 'Mantener en lugar fresco. Requiere récipe para entrega.'
  },
  {
    id: 3,
    nombre: 'Losartán Potásico 50mg',
    categoria: 'Cardiovascular',
    cantidad: 200,
    unidad: 'tabletas',
    hospital: 'Hospital Dr. José María Vargas',
    hospital_id: 2,
    disponible: true,
    donante: 'Cáritas de Venezuela',
    notas: 'Para control de pacientes crónicos e hipertensos damnificados.'
  },
  {
    id: 4,
    nombre: 'Solución Fisiológica 0.9% 500ml',
    categoria: 'Hidratación',
    cantidad: 350,
    unidad: 'frascos',
    hospital: 'Hospital Miguel Pérez Carreño',
    hospital_id: 3,
    disponible: true,
    donante: 'OPS/OMS Venezuela',
    notas: 'Insumo crítico para quirófanos y sala de emergencias.'
  },
  {
    id: 5,
    nombre: 'Gasas Estériles 10x10cm',
    categoria: 'Material de curación',
    cantidad: 1500,
    unidad: 'unidades',
    hospital: 'Hospital Universitario Dr. Ángel Larralde',
    hospital_id: 6,
    disponible: true,
    donante: 'Médicos Sin Fronteras',
    notas: 'Cajas selladas de 100 unidades listas para distribución interna.'
  },
  {
    id: 6,
    nombre: 'Insulina NPH Humana 100 UI/ml',
    categoria: 'Diabetes',
    cantidad: 25,
    unidad: 'viales',
    hospital: 'Hospital Central de Maracay',
    hospital_id: 5,
    disponible: true,
    donante: 'Donación Comunitaria Chacao',
    notas: 'Requiere refrigeración estricta entre 2°C y 8°C.'
  },
  {
    id: 7,
    nombre: 'Salbutamol Inhalador 100mcg',
    categoria: 'Respiratorio',
    cantidad: 0,
    unidad: 'inhaladores',
    hospital: 'Hospital Universitario de Maracaibo',
    hospital_id: 7,
    disponible: false,
    donante: 'Anónimo',
    notas: 'AGOTADO. Se espera reposición por vía aérea en las próximas 48 horas.'
  },
  {
    id: 8,
    nombre: 'Acetaminofén Pediátrico Jarabe 120mg/5ml',
    categoria: 'Analgésico',
    cantidad: 80,
    unidad: 'frascos',
    hospital: 'Hospital Central de San Cristóbal',
    hospital_id: 10,
    disponible: true,
    donante: 'Rotary Club San Cristóbal',
    notas: 'Para control de cuadros febriles en niños de los albergues temporales.'
  },
  {
    id: 9,
    nombre: 'Ceftriaxona 1g IV',
    categoria: 'Antibiótico',
    cantidad: 110,
    unidad: 'ampollas',
    hospital: 'Hospital Dr. Manuel Núñez Tovar',
    hospital_id: 9,
    disponible: true,
    donante: 'Acnur Venezuela',
    notas: 'Antibiótico de amplio espectro para traumatismos complicados.'
  },
  {
    id: 10,
    nombre: 'Adrenalina Ampollas 1mg/ml',
    categoria: 'Otro',
    cantidad: 50,
    unidad: 'ampollas',
    hospital: 'Hospital Universitario de Caracas (HUC)',
    hospital_id: 1,
    disponible: true,
    donante: 'Ministerio de Salud',
    notas: 'Insumo de soporte vital para carros de paro cardiorrespiratorio.'
  }
];
