import { Hospital, Paciente, PacienteDetalle, Insumo, Transporte } from './types';

export const MOCK_HOSPITALES: Hospital[] = [
  { id: 1, nombre: 'Hospital Universitario de Caracas (HUC)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4897, lng: -66.8894, telefono: '(0212) 605-4050' },
  { id: 2, nombre: 'Hospital Dr. José María Vargas', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5173, lng: -66.9189, telefono: '(0212) 862-9965' },
    { id: 3, nombre: 'Hospital Dr. Miguel Pérez Carreño', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4820, lng: -66.9610, telefono: '(0212) 472-8472' },
    { id: 4, nombre: 'Hospital Dr. Domingo Luciani', municipio: 'Sucre', estado: 'Miranda', lat: 10.4862, lng: -66.8153, telefono: '(0212) 205-6501' },
  { id: 5, nombre: 'Hospital Central de Maracay', municipio: 'Girardot', estado: 'Aragua', lat: 10.2522, lng: -67.5819, telefono: '(0243) 246-1212' },
  { id: 6, nombre: 'Hospital Universitario Dr. Ángel Larralde', municipio: 'Valencia', estado: 'Carabobo', lat: 10.2241, lng: -68.0163, telefono: '(0241) 871-6100' },
  { id: 7, merge_original: true, nombre: 'Hospital Universitario de Maracaibo', municipio: 'Maracaibo', estado: 'Zulia', lat: 10.6728, lng: -71.6353, telefono: '(0261) 752-0010' } as any, // Mantener id: 7
  { id: 8, nombre: 'Hospital Universitario Ruiz y Páez', municipio: 'Heres', estado: 'Bolívar', lat: 8.1283, lng: -63.5414, telefono: '(0285) 632-1515' },
  { id: 9, nombre: 'Hospital Dr. Manuel Núñez Tovar', municipio: 'Maturín', estado: 'Monagas', lat: 9.7497, lng: -63.1794, telefono: '(0291) 641-4011' },
  { id: 10, nombre: 'Hospital Central de San Cristóbal', municipio: 'San Cristóbal', estado: 'Táchira', lat: 7.7656, lng: -72.2198, telefono: '(0276) 347-1010' },
  
  // Nuevos centros agregados para cobertura nacional completa (Segmentación Geográfica de Emergencia)
  { id: 11, nombre: 'Hospital Central Universitario Antonio María Pineda', municipio: 'Iribarren', estado: 'Lara', lat: 10.0754, lng: -69.3172, telefono: '(0251) 252-0303' },
  { id: 12, nombre: 'Instituto Autónomo Hospital Universitario de los Andes (IAHULA)', municipio: 'Libertador', estado: 'Mérida', lat: 8.5991, lng: -71.1448, telefono: '(0274) 240-1111' },
  { id: 13, nombre: 'Hospital Universitario Dr. Luis Razetti (Barcelona)', municipio: 'Simón Bolívar', estado: 'Anzoátegui', lat: 10.1342, lng: -64.6853, telefono: '(0281) 263-4207' },
  { id: 14, nombre: 'Hospital Dr. Alfredo Van Grieken', municipio: 'Miranda', estado: 'Falcón', lat: 11.4114, lng: -69.6736, telefono: '(0268) 252-1112' },
  { id: 15, nombre: 'Hospital Universitario Antonio Patricio de Alcalá', municipio: 'Sucre', estado: 'Sucre', lat: 10.4533, lng: -64.1824, telefono: '(0293) 431-2020' },
  { id: 16, nombre: 'Hospital Dr. Luis Ortega', municipio: 'Mariño', estado: 'Nueva Esparta', lat: 10.9575, lng: -63.8583, telefono: '(0295) 261-1224' },
  { id: 17, nombre: 'Hospital Dr. Miguel Óraá', municipio: 'Guanare', estado: 'Portuguesa', lat: 9.0414, lng: -69.7483, telefono: '(0257) 251-1100' },
  { id: 18, nombre: 'Hospital Universitario Dr. Pedro Emilio Carrillo', municipio: 'Valera', estado: 'Trujillo', lat: 9.3178, lng: -70.6033, telefono: '(0271) 221-5050' },
  { id: 19, nombre: 'Hospital Dr. Luis Razetti (Barinas)', municipio: 'Barinas', estado: 'Barinas', lat: 8.6225, lng: -70.2119, telefono: '(0273) 541-1111' },
  { id: 20, nombre: 'Hospital Dr. José María Vargas — IVSS La Guaira', municipio: 'Vargas', estado: 'La Guaira', lat: 10.5983, lng: -66.9322, telefono: '(0212) 227-1468' },
  { id: 21, nombre: 'Hospital Dr. Israel Ranuárez Balza', municipio: 'Juan Germán Roscio', estado: 'Guárico', lat: 9.9114, lng: -67.3581, telefono: '(0246) 431-1522' },
  { id: 22, nombre: 'Hospital Dr. Egor Nucete', municipio: 'Ezequiel Zamora', estado: 'Cojedes', lat: 9.6533, lng: -68.5833, telefono: '(0258) 251-3011' },
  { id: 23, nombre: 'Hospital Dr. Pablo Acosta Ortiz', municipio: 'San Fernando', estado: 'Apure', lat: 7.8933, lng: -67.4722, telefono: '(0247) 341-0811' },
  { id: 24, nombre: 'Hospital Central Dr. Plácido Daniel Rodríguez Rivero', municipio: 'San Felipe', estado: 'Yaracuy', lat: 10.3392, lng: -68.7422, telefono: '(0254) 231-1055' },
  { id: 25, nombre: 'Hospital Dr. José Gregorio Hernández (Puerto Ayacucho)', municipio: 'Atures', estado: 'Amazonas', lat: 5.6639, lng: -67.6256, telefono: '(0248) 521-0111' },
  { id: 26, text: 'Hospital Dr. Luis Razetti (Tucupita)', municipio: 'Tucupita', estado: 'Delta Amacuro', lat: 9.0603, lng: -62.0514, telefono: '(0287) 721-1212' } as any, // Mantener tipo para delta
  { id: 27, nombre: 'Ciudad Hospitalaria Dr. Enrique Tejera (CHET)', municipio: 'Valencia', estado: 'Carabobo', lat: 10.1692, lng: -68.0125, telefono: '(0241) 831-2022' },
  { id: 28, nombre: 'Hospital General Dr. Felipe Guevara Rojas', municipio: 'Simón Rodríguez', estado: 'Anzoátegui', lat: 8.8833, lng: -64.2444, telefono: '(0283) 235-5022' },
  { id: 29, nombre: 'Hospital Dr. Rafael Calles Sierra', municipio: 'Carirubana', estado: 'Falcón', lat: 11.6975, lng: -70.1833, telefono: '(0269) 247-1122' },
  { id: 30, nombre: 'Hospital Dr. Raúl Leoni (Guaiparo)', municipio: 'Caroní', estado: 'Bolívar', lat: 8.3514, lng: -62.6514, telefono: '(0286) 931-1122' },
  { id: 31, nombre: 'Hospital Dr. Victorino Santaella', municipio: 'Guaicaipuro', estado: 'Miranda', lat: 10.3139, lng: -67.0403, telefono: '(0212) 364-0000' },
  { id: 32, nombre: 'Hospital Dr. de Niños J.M. de los Ríos', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5103, lng: -66.9031, telefono: '(0212) 574-3511' },

  // Nuevos centros reportados con teléfonos de emergencia confirmados por el usuario
  { id: 33, nombre: 'Clínica CCCT', municipio: 'Chacao', estado: 'Miranda', lat: 10.4912, lng: -66.8375, telefono: '(0212) 959-6444' },
  { id: 34, nombre: 'Clínica El Ávila', municipio: 'Chacao', estado: 'Miranda', lat: 10.4968, lng: -66.8450, telefono: '(0212) 276-1111' },
  { id: 35, nombre: 'Cruz Roja Venezolana — Sede La Candelaria (Caracas)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5042, lng: -66.9001, telefono: '(0212) 571-4380' },
  { id: 36, nombre: 'Grupo Médico Santa Paula', municipio: 'Baruta', estado: 'Miranda', lat: 10.4632, lng: -66.8322, telefono: '(0212) 917-6200' },
  { id: 37, nombre: 'Hospital Ana Francisca Pérez de León II (Petare)', municipio: 'Sucre', estado: 'Miranda', lat: 10.4795, lng: -66.8054, telefono: '(0212) 256-8448' },
  { id: 38, nombre: 'Hospital Ciudad Caribia', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5364, lng: -66.9532, telefono: '(0412) 377-1206' },
  { id: 39, nombre: 'Hospital Dr. José Gregorio Hernández (Magallanes)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5350, lng: -66.9420, telefono: '(0212) 862-2910' },
  { id: 40, nombre: 'Hospital Militar Universitario Dr. Carlos Arvelo', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4988, lng: -66.9242, telefono: '(0212) 406-1241' },
  { id: 41, nombre: 'Hospital Periférico de Catia (Dr. Ricardo Baquero González)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5284, lng: -66.9382, telefono: '(0212) 870-2266' },
  { id: 42, nombre: 'Hospital Periférico de Coche', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4674, lng: -66.9312, telefono: '(0212) 681-1133' },
  { id: 43, nombre: 'Materno Infantil del Valle (Hugo Chávez Frías)', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4578, lng: -66.8924, telefono: '(0212) 671-5902' },
  { id: 44, nombre: 'Policlínica La Arboleda', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5124, lng: -66.9015, telefono: '(0212) 550-1811' },
  { id: 45, nombre: 'Policlínica Santiago de León', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4905, lng: -66.8682, telefono: '(0212) 762-9025' },
  { id: 46, nombre: 'Policlínica David Lobo', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5050, lng: -66.9080, telefono: '(0212) 541-5465' },
  { id: 47, nombre: 'Policlínica Las Mercedes', municipio: 'Baruta', estado: 'Miranda', lat: 10.4815, lng: -66.8612, telefono: '(0212) 993-2323' },
  { id: 48, nombre: 'Sede del Sebin (La Guaira)', municipio: 'Vargas', estado: 'La Guaira', lat: 10.5925, lng: -66.9410, telefono: '(0212) 541-7656' },
  { id: 49, nombre: 'IVSS — Hospital General de Misiones Nuevas Generaciones Hugo Chávez', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.4950, lng: -66.9110, telefono: '(0212) 801-1000' },
  { id: 50, nombre: 'Clínica Canes', municipio: 'Libertador', estado: 'Distrito Capital', lat: 10.5064, lng: -66.9309, telefono: '(0212) 471-4848' }
];

export const MOCK_PACIENTES: PacienteDetalle[] = [
  {
    "id": 1,
    "nombre": "ABDLY ABDELYS",
    "edad": 28,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": "***624",
    "procedencia": "Caracas",
    "ingreso_detalle": "Ingresado por emergencia de sismo. Estable."
  },
  {
    "id": 2,
    "nombre": "ABELLO MATILDE",
    "edad": 36,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. Domingo Luciani",
    "hospital_id": 4,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación médica."
  },
  {
    "id": 3,
    "nombre": "Abello Wilmari",
    "edad": 36,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. Domingo Luciani",
    "hospital_id": 4,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Petare",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 4,
    "nombre": "ABREU REINA MARGARITA",
    "edad": 60,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": "***251",
    "procedencia": "Caracas",
    "ingreso_detalle": "En evaluación."
  },
  {
    "id": 5,
    "nombre": "ABREU REINA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": true,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Posible duplicado de Reina Margarita."
  },
  {
    "id": 6,
    "nombre": "ABREU REYNA MARGARITA",
    "edad": 60,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": true,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Duplicado confirmado."
  },
  {
    "id": 7,
    "nombre": "ACEVEDO ROSANGEL",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "En emergencias."
  },
  {
    "id": 8,
    "nombre": "ACOSTA ANGEL",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Heridas leves."
  },
  {
    "id": 9,
    "nombre": "ACOSTA DANILSA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 10,
    "nombre": "Acosta De Barazarte Danilsa Yris",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 11,
    "nombre": "Acosta Edelmira",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. Domingo Luciani",
    "hospital_id": 4,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control de pánico."
  },
  {
    "id": 12,
    "nombre": "ACOSTA JAIRO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Fractura leve."
  },
  {
    "id": 13,
    "nombre": "ACOSTA MARCO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 14,
    "nombre": "Acosta Marcos",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": true,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Duplicado."
  },
  {
    "id": 15,
    "nombre": "ACOSTA RAMON",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control de hipertensión."
  },
  {
    "id": 16,
    "nombre": "ACUÑA JESUS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 17,
    "nombre": "ADAMES LORENA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Politraumatismo leve."
  },
  {
    "id": 18,
    "nombre": "ADAN LUIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Herida en cuero cabelludo."
  },
  {
    "id": 19,
    "nombre": "ADRIAN JHOANNY",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Crisis de ansiedad."
  },
  {
    "id": 20,
    "nombre": "ADRIAN MARIO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Traumatismo cerrado."
  },
  {
    "id": 21,
    "nombre": "ADRIANZA JONATHAN",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Contusiones."
  },
  {
    "id": 22,
    "nombre": "AGAMEZ MIRIAN",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 23,
    "nombre": "AGUANA ANGEL",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 24,
    "nombre": "AGUANA LUIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Esguince tobillo."
  },
  {
    "id": 25,
    "nombre": "Aguiar Eladia",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Universitario de Caracas (HUC)",
    "hospital_id": 1,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En emergencias."
  },
  {
    "id": 26,
    "nombre": "AGUIAR EMILIO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 27,
    "nombre": "AGUILAR ENMA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Crisis hipertensiva."
  },
  {
    "id": 28,
    "nombre": "AGUILAR GABRIELA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 29,
    "nombre": "AGUILAR LISBETH",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Contusión cerebral leve."
  },
  {
    "id": 30,
    "nombre": "AGUILAR RAISA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 31,
    "nombre": "AGUILERA EDINSON",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 32,
    "nombre": "AGUILERA ISABEL",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control cardiológico."
  },
  {
    "id": 33,
    "nombre": "AGUILERA JOSUE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Fractura leve."
  },
  {
    "id": 34,
    "nombre": "AGUILERA LORENZO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Heridas superficiales."
  },
  {
    "id": 35,
    "nombre": "AGUILERA MARIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 36,
    "nombre": "AGUIN JOSMER",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 37,
    "nombre": "AGUIRRE GLEYDE",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Crisis de ansiedad."
  },
  {
    "id": 38,
    "nombre": "AGUIRRE MERCEDES",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 39,
    "nombre": "AGUIRRE YESSICA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Heridas cortantes."
  },
  {
    "id": 40,
    "nombre": "Alarcon Hector",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 41,
    "nombre": "ALARCON JAVIER",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control médico."
  },
  {
    "id": 42,
    "nombre": "ALARCON LUISA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Politraumatismo."
  },
  {
    "id": 43,
    "nombre": "ALASTRE GLENYS",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 44,
    "nombre": "ALBARRAN ARGENIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Herida en pierna."
  },
  {
    "id": 45,
    "nombre": "ALBARRAN ARGENIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 46,
    "nombre": "ALCALA ANGELICA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Esguince."
  },
  {
    "id": 47,
    "nombre": "ALCALA MANUEL",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Politraumatismo."
  },
  {
    "id": 48,
    "nombre": "ALCALA MIGUEL",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 49,
    "nombre": "ALCALA NESTOR",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 50,
    "nombre": "ALCALA NORELYS",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En emergencias."
  },
  {
    "id": 51,
    "nombre": "ALCALA NORELYS",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 52,
    "nombre": "ALCALA NORELYS YULIMAR",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": true,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Posible duplicado."
  },
  {
    "id": 53,
    "nombre": "ALCEGA MILENA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control tensional."
  },
  {
    "id": 54,
    "nombre": "ALCORTA LUIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Fractura leve."
  },
  {
    "id": 55,
    "nombre": "ALDANA ALICIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 56,
    "nombre": "ALDANA EDUARDO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Politraumatismo leve."
  },
  {
    "id": 57,
    "nombre": "ALDANA JOSE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Esguince."
  },
  {
    "id": 58,
    "nombre": "ALDANA KATERINE",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Herida en brazo."
  },
  {
    "id": 59,
    "nombre": "ALDANA REBECA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control de pánico."
  },
  {
    "id": 60,
    "nombre": "ALFARO MARIANNY",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 61,
    "nombre": "ALFONZO EMILIANO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Heridas cortantes."
  },
  {
    "id": 62,
    "nombre": "ALFONZO EMILIANO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 63,
    "nombre": "ALFONZO MAGALYS",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 64,
    "nombre": "ALFONZO YRENE",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Crisis de pánico."
  },
  {
    "id": 65,
    "nombre": "ALISTE ISIDRA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control médico."
  },
  {
    "id": 66,
    "nombre": "ALMEA MARIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 67,
    "nombre": "ALMEA MARIA GREGORIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": true,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Posible duplicado."
  },
  {
    "id": 68,
    "nombre": "ALMENDOZA CARMEN",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 69,
    "nombre": "ALMENDOZA JORGE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Fractura leve."
  },
  {
    "id": 70,
    "nombre": "ALTUBE GERARDO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Herida en pierna."
  },
  {
    "id": 71,
    "nombre": "ALVARADO ALEXANDER",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 72,
    "nombre": "ALVARADO CARLOS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Control de trauma."
  },
  {
    "id": 73,
    "nombre": "ALVARADO ELIZABETH",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Crisis hipertensiva."
  },
  {
    "id": 74,
    "nombre": "ALVARADO JESUS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 75,
    "nombre": "ALVARADO JOSE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 76,
    "nombre": "ALVARADO LUIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Contusiones."
  },
  {
    "id": 77,
    "nombre": "ALVARADO MARIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 78,
    "nombre": "ALVARADO NELLY",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Politraumatismo."
  },
  {
    "id": 79,
    "nombre": "ALVARADO YELITZA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Crisis de ansiedad."
  },
  {
    "id": 80,
    "nombre": "ALVAREZ ALFREDO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Fractura leve."
  },
  {
    "id": 81,
    "nombre": "ALVAREZ ALICIA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 82,
    "nombre": "ALVAREZ ANA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "En emergencias."
  },
  {
    "id": 83,
    "nombre": "ALVAREZ DANIELA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 84,
    "nombre": "ALVAREZ FRANCIS",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Crisis de pánico."
  },
  {
    "id": 85,
    "nombre": "ALVAREZ INGRID",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Control de hipertensión."
  },
  {
    "id": 86,
    "nombre": "ALVAREZ JAIRO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Herida leve."
  },
  {
    "id": 87,
    "nombre": "ALVAREZ JOSE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Contusiones."
  },
  {
    "id": 88,
    "nombre": "ALVAREZ JOSE",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 89,
    "nombre": "ALVAREZ LISBETH",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Crisis de pánico."
  },
  {
    "id": 90,
    "nombre": "ALVAREZ MARCOS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 91,
    "nombre": "ALVAREZ MIGUEL",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Herida en brazo."
  },
  {
    "id": 92,
    "nombre": "ALVAREZ NESTOR",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 93,
    "nombre": "ALVAREZ RAMON",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 94,
    "nombre": "ALVAREZ ROSA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Crisis hipertensiva."
  },
  {
    "id": 95,
    "nombre": "ALVAREZ YOLANDA",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 96,
    "nombre": "ALZURO KEVIN",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 97,
    "nombre": "ALZURO LUIS",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Trauma leve."
  },
  {
    "id": 98,
    "nombre": "AMADIZ CARMEN",
    "edad": null,
    "sexo": "Femenino",
    "hospital": "Hospital Miguel Pérez Carreño",
    "hospital_id": 3,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "Estable."
  },
  {
    "id": 99,
    "nombre": "AMADO JUAN",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Dr. José María Vargas",
    "hospital_id": 2,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Caracas",
    "ingreso_detalle": "En observación."
  },
  {
    "id": 100,
    "nombre": "AMARILLO GUSTAVO",
    "edad": null,
    "sexo": "Masculino",
    "hospital": "Hospital Periférico de Catia (Dr. Ricardo Baquero González)",
    "hospital_id": 41,
    "ingreso_fecha": "2026-06-25",
    "estado": "hospitalizado",
    "posible_duplicado": false,
    "cedula_masked": null,
    "procedencia": "Catia",
    "ingreso_detalle": "Esguince."
  }
];


export const MOCK_INSUMOS: Insumo[] = [
  {
    id: 1,
    nombre: 'Ibuprofeno 400mg',
    categoria: 'Analgésico',
    cantidad: 120,
    unidad: 'tabletas',
    hospital: 'Hospital Universitario de Caracas (HUC)',
    hospital_id: 1,
    disponible: true,
    donante: 'Cruz Roja Venezolana',
    notas: 'Uso exclusivo para pacientes admitidos por la emergencia del sismo.'
  },
  {
    id: 2,
    nombre: 'Amoxicilina + Ácido Clavulánico 875/125mg',
    categoria: 'Antibiótico',
    cantidad: 45,
    unidad: 'blisters',
    hospital: 'Hospital Dr. Domingo Luciani',
    hospital_id: 4,
    disponible: true,
    donante: 'Iniciativa Privada FarmaAyuda',
    notas: 'Mantener en lugar fresco. Requiere récipe para entrega.'
  },
  {
    id: 3,
    nombre: 'Losartán Potásico 50mg',
    categoria: 'Cardiovascular',
    cantidad: 200,
    unidad: 'tabletas',
    hospital: 'Hospital Dr. José María Vargas',
    hospital_id: 2,
    disponible: true,
    donante: 'Cáritas de Venezuela',
    notas: 'Para control de pacientes crónicos e hipertensos damnificados.'
  },
  {
    id: 4,
    nombre: 'Solución Fisiológica 0.9% 500ml',
    categoria: 'Hidratación',
    cantidad: 350,
    unidad: 'frascos',
    hospital: 'Hospital Miguel Pérez Carreño',
    hospital_id: 3,
    disponible: true,
    donante: 'OPS/OMS Venezuela',
    notas: 'Insumo crítico para quirófanos y sala de emergencias.'
  },
  {
    id: 5,
    nombre: 'Gasas Estériles 10x10cm',
    categoria: 'Material de curación',
    cantidad: 1500,
    unidad: 'unidades',
    hospital: 'Hospital Universitario Dr. Ángel Larralde',
    hospital_id: 6,
    disponible: true,
    donante: 'Médicos Sin Fronteras',
    notas: 'Cajas selladas de 100 unidades listas para distribución interna.'
  },
  {
    id: 6,
    nombre: 'Insulina NPH Humana 100 UI/ml',
    categoria: 'Diabetes',
    cantidad: 25,
    unidad: 'viales',
    hospital: 'Hospital Central de Maracay',
    hospital_id: 5,
    disponible: true,
    donante: 'Donación Comunitaria Chacao',
    notas: 'Requiere refrigeración estricta entre 2°C y 8°C.'
  },
  {
    id: 7,
    nombre: 'Salbutamol Inhalador 100mcg',
    categoria: 'Respiratorio',
    cantidad: 0,
    unidad: 'inhaladores',
    hospital: 'Hospital Universitario de Maracaibo',
    hospital_id: 7,
    disponible: false,
    donante: 'Anónimo',
    notas: 'AGOTADO. Se espera reposición por vía aérea en las próximas 48 horas.'
  },
  {
    id: 8,
    nombre: 'Acetaminofén Pediátrico Jarabe 120mg/5ml',
    categoria: 'Analgésico',
    cantidad: 80,
    unidad: 'frascos',
    hospital: 'Hospital Central de San Cristóbal',
    hospital_id: 10,
    disponible: true,
    donante: 'Rotary Club San Cristóbal',
    notas: 'Para control de cuadros febriles en niños de los albergues temporales.'
  },
  {
    id: 9,
    nombre: 'Ceftriaxona 1g IV',
    categoria: 'Antibiótico',
    cantidad: 110,
    unidad: 'ampollas',
    hospital: 'Hospital Dr. Manuel Núñez Tovar',
    hospital_id: 9,
    disponible: true,
    donante: 'Acnur Venezuela',
    notas: 'Antibiótico de amplio espectro para traumatismos complicados.'
  },
  {
    id: 10,
    nombre: 'Adrenalina Ampollas 1mg/ml',
    categoria: 'Otro',
    cantidad: 50,
    unidad: 'ampollas',
    hospital: 'Hospital Universitario de Caracas (HUC)',
    hospital_id: 1,
    disponible: true,
    donante: 'Ministerio de Salud',
    notas: 'Insumo de soporte vital para carros de paro cardiorrespiratorio.'
  }
];

export const MOCK_MEDICAMENTOS = MOCK_INSUMOS;

export const CIUDADES_VENEZUELA: string[] = [
  'Caracas',
  'Maracay',
  'Valencia',
  'Maracaibo',
  'Barquisimeto',
  'San Cristóbal',
  'Mérida',
  'Barcelona',
  'Puerto La Cruz',
  'Maturín',
  'Ciudad Guayana',
  'Ciudad Bolívar',
  'Cumaná',
  'Porlamar',
  'Coro',
  'Punto Fijo',
  'San Fernando de Apure',
  'Barinas',
  'Guanare',
  'Trujillo',
  'San Felipe',
  'San Carlos',
  'Puerto Ayacucho',
  'Tucupita',
  'Los Teques',
  'La Guaira',
  'Guarenas',
  'Guatire',
  'Cabimas'
];

export const MOCK_TRANSPORTE: Transporte[] = [
  {
    id: 1,
    nombre: 'Carlos Augusto Mendoza',
    telefono: '+584123456789',
    ciudad: 'Caracas',
    vehiculo: 'Camioneta Pick-up Toyota Hilux 4x4',
    capacidad_personas: 4,
    capacidad_carga: '800 kg (Plataforma amplia para cajas o escombros)',
    disponible: true,
    notas: 'Disponible para traslados urgentes de heridos, agua mineral, plantas eléctricas o alimentos.'
  },
  {
    id: 2,
    nombre: 'María Gabriela Torres Rivas',
    telefono: '+584149876543',
    ciudad: 'Valencia',
    vehiculo: 'Microbús Encava (24 puestos)',
    capacidad_personas: 24,
    capacidad_carga: '1.5 Toneladas (Portaequipaje amplio)',
    disponible: true,
    notes: 'Disponible para el traslado de brigadas de rescate, personal médico o evacuación masiva de familias.'
  } as any, // fallback support
  {
    id: 3,
    nombre: 'José Gregorio Silva',
    telefono: '+584161112233',
    ciudad: 'Maracay',
    vehiculo: 'Sedán Toyota Corolla',
    capacidad_personas: 4,
    capacidad_carga: '100 kg (Maletero estándar)',
    disponible: true,
    notas: 'Disponibilidad inmediata para traslado de médicos, enfermeros o distribución rápida de medicamentos/insumos.'
  },
  {
    id: 4,
    nombre: 'Luis Eladio Rondón Pérez',
    telefono: '+584245556677',
    ciudad: 'Barquisimeto',
    vehiculo: 'Camión de Carga Ford 350',
    capacidad_personas: 2,
    capacidad_carga: '3.5 Toneladas (Plataforma abierta con lona)',
    disponible: true,
    notas: 'Ideal para trasladar cargamentos pesados de insumos hospitalarios, medicamentos o donaciones de gran escala.'
  },
  {
    id: 5,
    nombre: 'Andrés Eloy Blanco Orozco',
    telefono: '+584128889900',
    ciudad: 'San Cristóbal',
    vehiculo: 'Vehículo Rústico Jeep Machito',
    capacidad_personas: 5,
    capacidad_carga: '400 kg',
    disponible: true,
    notas: 'Apto para zonas de montaña difíciles, caminos obstruidos o con barro.'
  },
  {
    id: 6,
    nombre: 'Patricia Valentina Guerrero',
    telefono: '+584267778899',
    ciudad: 'Maracaibo',
    vehiculo: 'Van Hyundai H1 (Furgoneta)',
    capacidad_personas: 8,
    capacidad_carga: '800 kg',
    disponible: true,
    notas: 'Apoyo en traslado de suministros médicos fríos o personal voluntario entre Maracaibo y San Francisco.'
  },
  {
    id: 7,
    nombre: 'Francisco Javier Gil',
    telefono: '+584144445566',
    ciudad: 'La Guaira',
    vehiculo: 'Camioneta Sport Van Kia Sedona',
    capacidad_personas: 7,
    capacidad_carga: '300 kg',
    disponible: false,
    notas: 'Temporalmente inactivo por mantenimiento, disponible para planificar traslados programados.'
  }
];
